### ISSUE TITLE
Is it 4 windows?

### ISSUE THREAD

**Issue by DilikMusic** [arnaud-neny/rePlayer#10]
Because it is not working 4 me. win11x64.
Nothing happens

**Comment by arnaud-neny** [comment]
Yes, it's working on Windows 11. One possible cause of not working could be the windows defender blocking the app (when sometimes it wrongly thinks it's a malicious software).

**Comment by usualius** [comment]
it's also not working for me, but on win10 (x64). and windows defender didn't found anything malicious in it.
same thing happens on newly installed win10 on virtual machine. don't know what could be the problem.

**Comment by arnaud-neny** [comment]
Maybe there are some dump files in your user directory in AppData\Local\CrashDumps thatr can help me guess the issue

**Comment by usualius** [comment]
there's none. and it didn't crashes. it didn't start at all. "nothing happens", as dilik said.

**Comment by arnaud-neny** [comment]
I made a quick change in the 0.8.5 that might help. Please let me know.

**Comment by usualius** [comment]
now it's working. thank you.
