### ISSUE TITLE
TFMX local files import crashes on playback

### ISSUE THREAD

**Issue by LemonHard** [arnaud-neny/rePlayer#12]
Hi,
Nice work again,
i would suggest some features :)

Format : TFMX (The Final Musicsystem Extended) aka MDAT
Comes with 2 files : mdat (song) and smpl (samples)
Exemple with game Z-Out Amiga version :
```
Nom              Taille Taille relative Type                            Modifié  Attr   Description
Level1.mdat     8,07 Ko *               Fichier MDAT           15/05/1993 14:23 -a-----
Level2.mdat     8,12 Ko *               Fichier MDAT           15/05/1993 14:23 -a-----
Level3.mdat     7,37 Ko *               Fichier MDAT           15/05/1993 14:23 -a-----
Level4.mdat     14,4 Ko **              Fichier MDAT           15/05/1993 14:23 -a-----
Level5.mdat     15,1 Ko **              Fichier MDAT           15/05/1993 14:23 -a-----
Level6.mdat     5,54 Ko *               Fichier MDAT           15/05/1993 14:23 -a-----
Titel.mdat      11,4 Ko *               Fichier MDAT           26/10/1995 21:04 -a-----
Level1.smpl     24,7 Ko ***             Fichier SMPL           07/11/1991 14:39 -a-----
Level2.smpl     36,7 Ko ****            Fichier SMPL           20/04/1992 18:18 -a-----
Level3.smpl     36,7 Ko ****            Fichier SMPL           07/11/1991 14:39 -a-----
Level4.smpl     38,6 Ko ****            Fichier SMPL           07/11/1991 14:40 -a-----
Level5.smpl     38,6 Ko ****            Fichier SMPL           07/11/1991 14:40 -a-----
Level6.smpl     24,7 Ko ***             Fichier SMPL           07/11/1991 14:40 -a-----
Titel.smpl       143 Ko ****************Fichier SMPL           07/11/1991 14:40 -a-----
```
https://www.vgmpf.com/Wiki/index.php?title=MDAT
in the past i was able to play them from xmplay with Deli plugin, but that plugin is outdated and playback is f....
Thanks !
(i can provide samples)

also exists with these extensions (game Apidya, Amiga), that doesn't help...
```
Nom              Taille Taille relative Type                            Modifié  Attr   Description
Apidya-END.SAM   202 Ko ****************Fichier SAM            04/04/1994 01:39 -a-----
Apidya-LVL1.SAM 62,1 Ko *****           Fichier SAM            04/04/1994 01:39 -a-----
Apidya-LVL2.SAM 36,1 Ko ***             Fichier SAM            04/04/1994 01:39 -a-----
Apidya-LVL3.SAM 46,2 Ko ****            Fichier SAM            04/04/1994 01:39 -a-----
Apidya-LVL4.SAM 67,1 Ko *****           Fichier SAM            04/04/1994 01:39 -a-----
Apidya-LVL5.SAM 63,5 Ko *****           Fichier SAM            07/04/1994 01:53 -a-----
Apidya-TITL.SAM  128 Ko **********      Fichier SAM            04/04/1994 01:39 -a-----
Apidya-END.tfx  12,4 Ko *               Fichier TFX            04/04/1994 01:39 -a-----
Apidya-LVL1.TFX 7,95 Ko *               Fichier TFX            04/04/1994 01:39 -a-----
Apidya-LVL2.TFX 10,1 Ko *               Fichier TFX            04/04/1994 01:39 -a-----
Apidya-LVL3.TFX 7,64 Ko *               Fichier TFX            04/04/1994 01:39 -a-----
Apidya-LVL4.TFX 9,48 Ko *               Fichier TFX            04/04/1994 01:39 -a-----
Apidya-LVL5.TFX 4,81 Ko                 Fichier TFX            04/04/1994 01:39 -a-----
Apidya-TITL.TFX 6,88 Ko *               Fichier TFX            04/04/1994 01:39 -a-----

```

**Comment by LemonHard** [comment]
Sorry, it seems you have support for TFMX, i see it in the replays but keep having instant crash when playback starts.
Log to file shows nothing.

**Comment by arnaud-neny** [comment]
Ok, I'm able to repro the crash after the file import. I'm going to prevent the crash but the actual import feature from files doesn't support songs with multiples files (such as tfmx). You can play it just by drag'n'drop it on the replayer, or import it online (imprt songs or import artist).

**Comment by LemonHard** [comment]
Yes, that works the way you said. It was easy to find Z-Out & Apidya, subsongs & playback as expected.
i understand that rePlayer is mostly a good tool to start a new personal db from good online resources.
i admit that i started to use it as past players, opening files from self local/imported files from around the web.

rePlayer seems a good alternative to play all these exotics fabulous music formats, all in one.
just few ideas for later :
- local import : folders (*.*), recursive(*/*), archives (*.zip) (but i know it's not first goal of rePlayer)
- online import : Random button ! or Popular songs ! (i don't know what to search as limited to song & artist fields, it requires that you know what you search, lets say i wanna discover new things ?)

**Comment by arnaud-neny** [comment]
Ok, finally worked it out. File importer is refactored, and import mostly everything based on if it's playable or not (but still having the possibility to force some data to go in the library). It's parsing files, directories and archives, and rebuild everything if there are some multi-files songs (such as tfmx).

**Comment by LemonHard** [comment]
Thanks :)
