### ISSUE TITLE
Add support for .fur file format

### ISSUE THREAD

**Issue by Speedvicio** [arnaud-neny/rePlayer#13]
Can you add the support for [.fur (furnace)](https://github.com/tildearrow/furnace) file format?
rePlayer could be the first audio player with this addiction.

**Comment by arnaud-neny** [comment]
It's already in my todo list, tried to look at it once but it's a huge code database so I'm postponing it until I find the courage to dive into it.

**Comment by arnaud-neny** [comment]
Ok, I've started the integration of Furnace 0.6. Let's hope I will not encounter any hard issues.

**Comment by arnaud-neny** [comment]
Done at v0.11.0

**Comment by Speedvicio** [comment]
> Done at v0.11.0

You are my hero,,❤️
