### ISSUE TITLE
Patterns display not zooming as the window

### ISSUE THREAD

**Issue by kenshigros** [arnaud-neny/rePlayer#18]
Hi.Love this very powerful player!!!!
Yes the window concerning the patterns displayed is not sizing with the windows on my windows 11 PC computer.The patterns stay tiny whatever the window size...
Thank you
The rest is very very good
Mercy Arnaud
PS:rePlayer is a nice name coming from Replay as a nickname :)

**Comment by arnaud-neny** [comment]
Hi,

and thank you for the nice comments :)
There is no zooming on the pattern display, but I will try to add an option to enable it (from the context menu when you right click in the pattern display window).

**Comment by kenshigros** [comment]
Hi
It is not about zooming actually but when you are using a display resolution of 4K or above the patterns display is very tiny on screen
🤔
Envoyé de mon iPhone

Le 4 mai 2024 à 19:45, Arnaud Neny ***@***.***> a écrit :

﻿

Hi,

and thank you for the nice comments :)
There is no zooming on the pattern display, but I will try to add an option to enable it (from the context menu when you right click in the pattern display window).

**Comment by arnaud-neny** [comment]
C'est dans la boîte!

Scaled by default to fit in the window, or you can adjust set a scale from 1 to 4.

Merci!

**Comment by kenshigros** [comment]
Merci beaucoup
Your program is marvellous!

Envoyé de mon iPhone

Le 4 mai 2024 à 22:16, Arnaud Neny ***@***.***> a écrit :

﻿

Closed #18<https://github.com/arnaud-neny/rePlayer/issues/18> as completed.
