### ISSUE TITLE
Win 7 32 bit release do not work.

### ISSUE THREAD

**Issue by Speedvicio** [arnaud-neny/rePlayer#19]
Hi!
I'm running the last 32 bit version of your player on a Windows 7 32 bit OS.
The program do not start without error or log, probably due to unsupported video backed (I'm using a Asus eeepc 701 with intel integrated gma915 GPU).
Imgui run onto furnace in this pc using sdl2.

**Comment by arnaud-neny** [comment]
imgui doesn't support multi-viewport with sdl2 :(

**Comment by arnaud-neny** [comment]
Found an old laptop in my drawer yesterday working in win7; I was able to find some issues with the win32 version and I made it working. Let's hope it will go further on yours. You'll have to redownload the release as the runtime wasn't working properly.

**Comment by Speedvicio** [comment]
> Found an old laptop in my drawer yesterday working in win7; I was able to find some issues with the win32 version and I made it working. Let's hope it will go further on yours. You'll have to redownload the release as the runtime wasn't working properly.

You are my hero <3, all working fine, the only problem is the dB creation that requires a lot of time, but this is a problem of my pc that run at 900 mhz
