### ISSUE TITLE
RePlayer 0.15.18

### ISSUE THREAD

**Issue by Speedvicio** [arnaud-neny/rePlayer#22]
Seem that 32 bit release do not want to start anymore without no crash report

**Comment by Speedvicio** [comment]
thx for the interest

**Comment by arnaud-neny** [comment]
Just for the heads up, there is a breaking change in the 0.15.20 where the win32 runtime is now rePlayer-win32.exe.
The autoupdate from previous versions will crash but you just need to use the new runtime (it's just to be able to have both versions lived in the same directory)
