### ISSUE TITLE
Decoders default to surround?

### ISSUE THREAD

**Issue by fotisandstuff** [arnaud-neny/rePlayer#23]
Hello! I have started playing around with rePlayer and it is great! However, I noticed that many decoders, including Game-Music-Emu, OpenMPT, sc68 and others, have Surround as the default option. This results to phasey distorted sound when I'm listening with headphones and I have to set each decoder to Stereo manually. Is there an option to have them all set to Stereo by default?

**Comment by arnaud-neny** [comment]
Hi, sorry, there is no global options for all decoders (there is a task in the todo list to rework the settings system). There are not much decoders with surround and when you changed it in the settings, it is saved so you'll have to do it only once.

**Comment by fotisandstuff** [comment]
Thank you!
