### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by heretik3d** [arnaud-neny/rePlayer#25]
Hello, I believe this is amazing player (looks like SNDH Archive Player from Leonard/Oxygene) but unfortunately not working for me because I have Intel and there's a bug saying:

"x64 version doesn't work on Intel® HD Graphics 4600 (fails in root signature or pipeline state creation, but without the hardware, I can't pinpoint the cause)"

...I checked all versions of rePlayer. Please fix this bug. I need this amazing sc68 player. Thank you.

**Comment by arnaud-neny** [comment]
You can try running the win32 version

**Comment by heretik3d** [comment]
Thank you, latest 0.16.6 win32 release working after fix some VCRUNTIME140.dll issues. Are you also planning to release android version in future? It would be amazing.

**Comment by arnaud-neny** [comment]
No android release for now (I don't have enough spare time and also never worked on android)
