### ISSUE TITLE
Bug on wav export

### ISSUE THREAD

**Issue by Speedvicio** [arnaud-neny/rePlayer#4]
Meanwhile, I wanted to thank you for adding wav export and track looping, unluckly the wav export has a bug.

When you start the export, the program start to export the track, during this phase you cannot stop the process and the user must to wait the finished task.
The task ended with the program clousure and the obtained file can be played by audio player , but can be edited by specific software (using audacity and wavosaur).
Also if it is not more difficult, can you add the batch wav export of single channells?

Thx in advance.

**Comment by arnaud-neny** [comment]
The cancel of the export will be easy to do. If the program closed, it's a crash. Do you have the files you are trying to export so I can reproduce. All the tests I've done passed fine and I was always able to open the wav in audacity and vlc. So it might be to do with the crash or the file format. Unfortunately I'm not going to do the single channel export.

**Comment by Speedvicio** [comment]
> The cancel of the export will be easy to do. If the program closed, it's a crash. Do you have the files you are trying to export so I can reproduce. All the tests I've done passed fine and I was always able to open the wav in audacity and vlc. So it might be to do with the crash or the file format. Unfortunately I'm not going to do the single channel export.

I have tested the export function during a started playing file.
Could be this the cause of crash?

**Comment by arnaud-neny** [comment]
I pushed the changes in the 0.4.1; but I couldn't repro the crash, even while playing songs (it's independent anyway).
For the single channel export, I put the feature request in the backlog. Maybe someday I'll have the courage to refactor the systemto allow it.
