### ISSUE TITLE
.GBS files are being played through Game Music Emu, although there's a GBSPlay Replay.

### ISSUE THREAD

**Issue by TheDuccinator** [arnaud-neny/rePlayer#7]
As shown here

![replayer2](https://github.com/arnaud-neny/rePlayer/assets/66538032/fedff0d3-c754-499f-b619-4d73ac7e4c2a)
![replayer1](https://github.com/arnaud-neny/rePlayer/assets/66538032/bf417fa0-fa63-4ada-9779-64f9fabcda1e)

**Comment by arnaud-neny** [comment]
This is not an issue. Right now, gme has priority over gbsplay. If you to use gbsplay, just edit the song (open the song editor), and change the replay manually (and save).
In the future, there will be a global replay selection in the settings for each extension.
