### ISSUE TITLE
Clarify license?

### ISSUE THREAD

**Issue by tildearrow** [arnaud-neny/rePlayer#8]
The current license is rather concise, but also unspecific:

- Is modification allowed?
- What about commercial use?
- Attribution requirements?
- Do I get a warranty by default?

Curiously, this project used a MIT license before. Did something happen?

**Comment by arnaud-neny** [comment]
Someone remind me as it's using a lot of 3rd parties, the MIT license wasn't appropriate. So I removed it. I really don't know which one to choose, as each 3rd party has its own licence. But modifications are allowed, and I expect nobody does a commercial use of it.

**Comment by Speedvicio** [comment]
Could be CC0 licenses compatible with others licenses?

**Comment by arnaud-neny** [comment]
Maybe CC-BY-NC-SA?

**Comment by tildearrow** [comment]
"NC" would break the GPL as used by ASAP.
