### ISSUE TITLE
Build for Win 7 32bit

### ISSUE THREAD

**Issue by Speedvicio** [arnaud-neny/rePlayer#9]
If it's not a too complex job, could you create a build compatible with win 7 32bit?

**Comment by arnaud-neny** [comment]
no, this system is deprecated

**Comment by Epictyphlosion** [comment]
Seconded. Plus I feel DX12 is way too much for a simple module player.

**Comment by arnaud-neny** [comment]
I'll think about it. I'll need to update some libraries to work on 32 bits and add a proper gfx api wrapper.

**Comment by arnaud-neny** [comment]
The win32 runtime is available now to run starting from Windows 7 (not tested properly, just with the Windows 10 compatibility mode). I'm not supporting Windows XP as some system libraries are not available there.
If there are issues, please open a new issue.
